### ISSUE TITLE
Getting the paths as variable that are changed. (for micro packages deploy purpose)

### ISSUE THREAD

**Issue by softmarshmallow** [MarceloPrado/has-changed-path#11]
in my case, [see this repo](https://github.com/softmarshmallow/remote-ui)
there are several micro packages under `flutter/pakcages/**`

what i want to accomplish it to run each package deployment if each of them are changed. with the single workflow file.

some like this
```yml

match: flutter/packages/**

for: steps.path_changed
   run: publish ${{changed.name}}
```
