### ISSUE TITLE
fatal: bad revision 'HEAD~1'

### ISSUE THREAD

**Issue by tekumara** [MarceloPrado/has-changed-path#18]
My [builds are failing](https://github.com/tekumara/asu/runs/2258861919?check_suite_focus=true
) to detect that the file has changed:
```
Run marceloprado/has-changed-path@v1
  with:
    paths: asu/__init__.py
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.10/x64/lib
/usr/bin/git diff --quiet HEAD~1 HEAD -- asu/__init__.py
fatal: bad revision 'HEAD~1'
Code in the following paths hasn't changed: asu/__init__.py
```

**Comment by tekumara** [comment]
Looks like is because actions/checkout@v2 fetches with depth=1:
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +14bca51985e1e2426f26692f92c598c026d68a2c:refs/remotes/origin/main 
```

**Comment by tekumara** [comment]
To fix, set fetch-depth like so:
```
    - uses: actions/checkout@v2
      with:
        # so marceloprado/has-changed-path@v1 can detect changes
        fetch-depth: 1
```
